name: CI / CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: cd front; npm install;npm install axios; cd ..
      - run: cd front; npm run build; cd ..
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm test
  deploy:
    needs: [test]   
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy